### Get all users
GET http://localhost:3000/api/users

### Get a specific user by Username
GET http://localhost:3000/api/users/Test123 HTTP/1.1

### Post a new user
POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{
    "username": "Test123",
    "email": "test.doe@email.com",
    "password": "Password7&",
    "role": "admin"
}

### Update a user by Username
PUT http://localhost:3000/api/users/Test123 HTTP/1.1
Content-Type: application/json

{
    "email": "john.doe@updated.com"
}

### Delete a user by Username
DELETE http://localhost:3000/api/users/Test123 HTTP/1.1